# Generated by Django 5.2.17 on 2026-09-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acervo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DT', 'Digital'), ('FS', 'Físico')], default='DT', max_length=2, verbose_name='Tipo')),
                ('categoria', models.IntegerField(choices=[(0, '000 - Generalidades e Informação: Obras gerais, enciclopédias, jornais e biblioteconomia.'), (100, '100 - Filosofia e Psicologia: Ética, lógica e investigações sobre a mente humana.'), (200, '200 - Religião e Teologia: Mitologia, teologia e estudos sobre crenças e religiões.'), (300, '300 - Ciências Sociais e Direito: Política, economia, sociologia, educação e leis.'), (400, '400 - Linguística e Idiomas: Gramáticas, dicionários e estudos de línguas.'), (500, '500 – Ciências Puras (Exatas e Naturais): Matemática, física, química, biologia e astronomia.'), (600, '600 – Ciências Aplicadas (Tecnologia): Medicina, engenharia, agricultura e administração.'), (700, '700 – Artes e Recreação: Pintura, música, arquitetura, esportes e lazer.'), (800, '800 – Literatura: Poesia, romances, contos, crônicas e crítica literária.'), (900, '900 – História e Geografia: Biografias, viagens e acontecimentos históricos')], default=0, verbose_name='Categoria')),
                ('livro', models.ManyToManyField(to='Simulado.livro', verbose_name='livro')),
            ],
        ),
    ]
